sports = {
"1":"81diver",
"2":"Abu-san",
"3":"Ace of Diamond",
"4":"Aim for the Ace!",
"5":"Air Gear",
"6":"Akakichi no Eleven",
"7":"All Out!!",
"8":"Amanchu!",
"9":"Angels in the Court",
"10":"Animal Olympic Games",
"11":"Anima Yell!",
"12":"Arrow Emblem: Hawk of the Grand Prix",
"13":"Asahinagu",
"14":"Ashen Victor",
"15":"Ashita e Kick-off",
"16":"Ashita no Joe",
"17":"Attack No. 1",
"18":"Attack on Tomorrow",
"19":"Attacker You!",
"20":"Baby Steps",
"21":"Badminton Girl",
"22":"Baki the Grappler",
"23":"Bamboo Blade",
"24":"Bataashi Kingyo",
"25":"Big Windup!",
"26":"Blazing Transfer Student",
"27":"Break Shot",
"28":"Buzzer Beater",
"29":"Capeta",
"30":"Captain Tsubasa",
"31":"Cheer Boys!!",
"32":"Chihayafuru",
"33":"Crimson Hero",
"34":"Cross Game",
"35":"Cross Manage",
"36":"Dan Doh!!",
"37":"Dash!",
"38":"Dash Kappei",
"39":"Days",
"40":"Dear Boys",
"41":"Dive!!",
"42":"Dokaben",
"43":"Eyeshield 21",
"44":"Football Hawk",
"45":"Free!",
"46":"Ganba! Fly High",
"47":"Ganbare!! Tabuchi-kun!!",
"48":"Giant Killing",
"49":"Ginban Kaleidoscope",
"50":"Girl Got Game",
"51":"Go!! Southern Ice Hockey Club",
"52":"Gurazeni",
"53":"H2",
"54":"Haikyu!!",
"55":"Hajime no Ippo",
"56":"Hana-Kimi",
"57":"Hanebado!",
"58":"Harlem Beat",
"59":"Hikari no Densetsu",
"60":"Hikaru no Go",
"61":"Hinomaru Sumo",
"62":"How Heavy Are the Dumbbells You Lift?",
"63":"I'll",
"64":"Igaguri-kun [jp]",
"65":"Inazuma Eleven",
"66":"Initial D",
"67":"Inu Neko Jump!",
"68":"Iwa-Kakeru! -Climbing Girls-",
"69":"Jaja Uma Grooming Up!",
"70":"Karate Master",
"71":"Kenkō Zenrakei Suieibu Umishō",
"72":"King of Prism",
"73":"Kinnikuman",
"74":"Kizuna: Bonds of Love",
"75":"Kuroko's Basketball",
"76":"Mahjong Hishō-den: Naki no Ryū",
"77":"Major",
"78":"March Comes in Like a Lion",
"79":"Mars",
"80":"Megalo Box",
"81":"Midori no Makibaō",
"82":"Monkey Turn",
"83":"Musashi no Ken",
"84":"My Heavenly Hockey Club",
"85":"Nana Maru San Batsu",
"86":"Nononono",
"87":"One Outs",
"88":"One-pound Gospel",
"89":"Over Drive",
"90":"Ping Pong",
"91":"Pretty Rhythm",
"92":"Pretty Rhythm: Aurora Dream",
"93":"Pretty Rhythm: Dear My Future",
"94":"Pretty Rhythm: Rainbow Live",
"95":"Pretty Rhythm: All Star Selection",
"96":"The Prince of Tennis",
"97":"Princess Nine",
"98":"Pro Golfer Saru [jp]",
"99":"Real",
"100":"Rideback",
"101":"Rifle is Beautiful",
"102":"Ring ni Kakero",
"103":"Rough",
"104":"The Ryuo's Work is Never Done!",
"105":"Sabagebu!",
"106":"Saki",
"107":"Shion no Ō",
"108":"Shōjo Fight [jp]",
"109":"Slam Dunk",
"110":"Slow Step",
"111":"Speed Racer",
"112":"Star of the Giants",
"113":"Stella Women's Academy, High School Division Class C3",
"114":"Sugar Princess",
"115":"Super Yo-Yo",
"116":"Supinamarada!",
"117":"Suzuka",
"118":"Tiger Mask",
"119":"Touch",
"120":"Tough",
"121":"Tsurune",
"122":"Uma Musume Pretty Derby",
"123":"Waiting for Spring",
"124":"Welcome to the Ballroom",
"125":"Whistle!",
"126":"Yawara!",
"127":"Yowamushi Pedal",
"128":"Yuri on Ice"
}

action = {
"1": "Abashiri Family" ,
"2": "Absolute Duo",
"3": "A Certain Magical Index",
"4": "A Certain Magical Index II",
"5": "A Certain Magical Index: The Movie - The Miracle of Endymion",
"6": "A Certain Scientific Railgun",
"7": "A Certain Scientific Railgun",
"8": "A Certain Scientific Railgun",
"9": "AD Police",
"10": "A.D. Police: To Protect and Serve",
"11": "Aesthetica of a Rogue Hero",
"12": "Afro Samurai",
"13": "Afro Samurai: Resurrection",
"14": "Agent Aika",
"15": "Akira",
"16": "Angel Beats!",
"17": "Angel Beats! Stairway to Heaven",
"18": "Angel Beats! Hell's Kitchen",
"19": "Arabian Nights: Sinbad's Adventures",
"20": "Armitage III",
"21": "Armitage III: Poly-Matrix",
"22": "Armitage III: Dual-Matrix",
"23": "Armored Trooper Votoms",
"24": "Attack on Titan",
"25": "Attack on Titan: Part 1: Crimson Bow and Arrow",
"26": "Attack on Titan: Part 2: Wings of Freedom",
"27": "Baccano",
"28": "Battle Royal High School",
"29": "Berserk (1997)",
"30": "Berserk (2016)",
"31": "Black Jack 21",
"32": "Black Lagoon",
"33": "Black Lagoon: The Second Barrage",
"34": "Black Lagoon: Roberta's Blood Trail",
"35": "Black Magic M-66",
"36": "Black Rock Shooter",
"37": "Black Rock Shooter",
"38": "Blade of the Immortal",
"39": "Blassreiter",
"40": "Bleach",
"41": "Bleach: Memories of Nobody",
"42": "Bleach: The DiamondDust Rebellion",
"43": "Bleach: Fade to Black",
"44": "Bleach: Hell Verse",
"45": "Blood+",
"46": "Blood-C",
"47": "Blood-C: The Last Dark",
"48": "Blood: The Last Vampire",
"49": "Blue Exorcist",
"50": "Blue Exorcist: The Movie",
"51": "Blue Exorcist: Kyoto Impure King Arc",
"52": "Blue Seed",
"53": "Blue Seed Beyond",
"54": "Btooom!",
"55": "Burn-Up Scramble",
"56": "Burst Angel",
"57": "Burst Angel - Episode Zero: Infinity",
"58": "Busou Renkin",
"59": "Cardfight! Vanguard",
"60": "Cardfight! Vanguard: Asia Circuit",
"61": "Cardfight! Vanguard: Link Joker",
"62": "Cardfight! Vanguard: Legion Mate",
"63": "Cardfight! Vanguard G",
"64": "Cardfight! Vanguard G: GIRS Crisis",
"65": "Cardfight! Vanguard G: Stride Gate",
"66": "Cardfight! Vanguard G NEXT",
"67": "Casshern Sins",
"68": "The Castle Of Cagliostro",
"69": "Chrome Shelled Regios",
"70": "Claymore",
"71": "Cutey Honey",
"72": "Cybuster",
"73": "Dance In The Vampire Bund",
"74": "Darker Than Black",
"75": "Darker Than Black: Beneath the Fully Bloomed Cherry Blossoms",
"76": "Darker Than Black: Gemini of the Meteor",
"77": "Darker Than Black: Origins",
"78": "Daughter of Twenty Faces",
"79": "Devil Hunter Yohko",
"80": "Devilman",
"81": "Devilman: The Birth",
"82": "Devilman: Demon Bird Sirene",
"83": "Digimon Adventure",
"84": "Digimon Adventure 02",
"85": "Digimon Adventure Tri.",
"86": "Digimon Data Squad",
"87": "Digimon Frontier",
"88": "Digimon Fusion",
"89": "Digimon Tamers",
"90": "Digimon Universe: Appli Monsters",
"91": "Dirty Pair",
"92": "Dirty Pair 2",
"93": "Dirty Pair: Affair of Nolandia",
"94": "Dirty Pair Flash",
"95": "Dirty Pair: Flight 005 Conspiracy",
"96": "Dirty Pair: Project Eden",
"97": "Dominion",
"98": "New Dominion: Tank Police",
"99": "Dragon Ball",
"100": "Dragon Ball GT",
"101": "Dragon Ball Super",
"102": "Dragon Ball Z",
"103": "Dragon Ball Z Kai",
"104": "Fullmetal Alchemist",
"105": "Fullmetal Alchemist: Brotherhood",
"106": "GetBackers",
"107": "Gurren Lagann",
"108": "Hajime no Ippo",
"109": "Hellsing",
"110": "JoJo's Bizarre Adventure",
"111": "JoJo's Bizarre Adventure: Adventure",
"112": "JoJo's Bizarre Adventure: Phantom Blood",
"113": "JoJo´s Bizarre Adventure: Stardust Crusaders",
"114": "JoJo's Bizarre Adventure: Diamond Is Unbreakable",
"115": "Naruto",
"116": "Naruto Shippuden",
"117": "One Piece",
"118": "Sonic X",
"119": "Sorcerous Stabber Orphen: Beginning",
"120": "Sorcerous Stabber Orphen: Revenge",
"121": "Sorcerous Stabber Orphen: Wayward Journey",
"122": "Soul Eater",
"123": "Sword Art Online",
"124": "Sword Art Online II",
"125": "Trinity Blood",
"126": "Neon Genesis Evangelion",
"127": "Virtua Fighter",
"128": "mob psycho 100"
}

sports = {
"1":"81diver",
"2":"Abu-san",
"3":"Ace of Diamond",
"4":"Aim for the Ace!",
"5":"Air Gear",
"6":"Akakichi no Eleven",
"7":"All Out!!",
"8":"Amanchu!",
"9":"Angels in the Court",
"10":"Animal Olympic Games",
"11":"Anima Yell!",
"12":"Arrow Emblem: Hawk of the Grand Prix",
"13":"Asahinagu",
"14":"Ashen Victor",
"15":"Ashita e Kick-off",
"16":"Ashita no Joe",
"17":"Attack No. 1",
"18":"Attack on Tomorrow",
"19":"Attacker You!",
"20":"Baby Steps",
"21":"Badminton Girl",
"22":"Baki the Grappler",
"23":"Bamboo Blade",
"24":"Bataashi Kingyo",
"25":"Big Windup!",
"26":"Blazing Transfer Student",
"27":"Break Shot",
"28":"Buzzer Beater",
"29":"Capeta",
"30":"Captain Tsubasa",
"31":"Cheer Boys!!",
"32":"Chihayafuru",
"33":"Crimson Hero",
"34":"Cross Game",
"35":"Cross Manage",
"36":"Dan Doh!!",
"37":"Dash!",
"38":"Dash Kappei",
"39":"Days",
"40":"Dear Boys",
"41":"Dive!!",
"42":"Dokaben",
"43":"Eyeshield 21",
"44":"Football Hawk",
"45":"Free!",
"46":"Ganba! Fly High",
"47":"Ganbare!! Tabuchi-kun!!",
"48":"Giant Killing",
"49":"Ginban Kaleidoscope",
"50":"Girl Got Game",
"51":"Go!! Southern Ice Hockey Club",
"52":"Gurazeni",
"53":"H2",
"54":"Haikyu!!",
"55":"Hajime no Ippo",
"56":"Hana-Kimi",
"57":"Hanebado!",
"58":"Harlem Beat",
"59":"Hikari no Densetsu",
"60":"Hikaru no Go",
"61":"Hinomaru Sumo",
"62":"How Heavy Are the Dumbbells You Lift?",
"63":"I'll",
"64":"Igaguri-kun [jp]",
"65":"Inazuma Eleven",
"66":"Initial D",
"67":"Inu Neko Jump!",
"68":"Iwa-Kakeru! -Climbing Girls-",
"69":"Jaja Uma Grooming Up!",
"70":"Karate Master",
"71":"Kenkō Zenrakei Suieibu Umishō",
"72":"King of Prism",
"73":"Kinnikuman",
"74":"Kizuna: Bonds of Love",
"75":"Kuroko's Basketball",
"76":"Mahjong Hishō-den: Naki no Ryū",
"77":"Major",
"78":"March Comes in Like a Lion",
"79":"Mars",
"80":"Megalo Box",
"81":"Midori no Makibaō",
"82":"Monkey Turn",
"83":"Musashi no Ken",
"84":"My Heavenly Hockey Club",
"85":"Nana Maru San Batsu",
"86":"Nononono",
"87":"One Outs",
"88":"One-pound Gospel",
"89":"Over Drive",
"90":"Ping Pong",
"91":"Pretty Rhythm",
"92":"Pretty Rhythm: Aurora Dream",
"93":"Pretty Rhythm: Dear My Future",
"94":"Pretty Rhythm: Rainbow Live",
"95":"Pretty Rhythm: All Star Selection",
"96":"The Prince of Tennis",
"97":"Princess Nine",
"98":"Pro Golfer Saru [jp]",
"99":"Real",
"100":"Rideback",
"101":"Rifle is Beautiful",
"102":"Ring ni Kakero",
"103":"Rough",
"104":"The Ryuo's Work is Never Done!",
"105":"Sabagebu!",
"106":"Saki",
"107":"Shion no Ō",
"108":"Shōjo Fight [jp]",
"109":"Slam Dunk",
"110":"Slow Step",
"111":"Speed Racer",
"112":"Star of the Giants",
"113":"Stella Women's Academy, High School Division Class C3",
"114":"Sugar Princess",
"115":"Super Yo-Yo",
"116":"Supinamarada!",
"117":"Suzuka",
"118":"Tiger Mask",
"119":"Touch",
"120":"Tough",
"121":"Tsurune",
"122":"Uma Musume Pretty Derby",
"123":"Waiting for Spring",
"124":"Welcome to the Ballroom",
"125":"Whistle!",
"126":"Yawara!",
"127":"Yowamushi Pedal",
"128":"Yuri on Ice"
}

sliceoflife = {
"1":"High School! Kimengumi",
"2":"Yokohama Kaidashi Kikō",
"3":"Kokoro Toshokan",
"4":"Shrine of the Morning Mist",
"5":"Azumanga Daioh",
"6":"Quiet Country Cafe",
"7":"Aria",
"8":"Strawberry Marshmallow",
"9":"Bartender",
"10":"Dobutsu no Mori",
"11":"Clannad",
"12":"Lucky Star",
"13":"Minami-ke",
"14":"Sketchbook ~full color's~",
"15":"Hyakko",
"16":"GA Geijutsuka Art Design Class",
"17":"Hidamari Sketch",
"18":"K-On!",
"19":"Ristorante Paradiso",
"20":"Student Council's Discretion",
"21":"And Yet the Town Moves",
"22":"Bakuman",
"23":"Mitsudomoe",
"24":"Tamayura",
"25":"Squid Girl",
"26":"Working!!",
"27":"A Channel",
"28":"Anohana: The Flower We Saw That Day",
"29":"From Up on Poppy Hill",
"30":"Hanasaku Iroha",
"31":"Nichijou",
"32":"Tamayura: Hitotose",
"33":"YuruYuri",
"34":"Daily Lives of High School Boys",
"35":"Hidamari Sketch x Honeycomb",
"36":"Hyōka",
"37":"Kill Me Baby",
"38":"Kimi to Boku 2",
"39":"Mysterious Girlfriend X",
"40":"Place to Place",
"41":"Shirokuma Cafe",
"42":"Teekyu",
"43":"Wolf Children",
"44":"Yurumates 3D",
"45":"Free!",
"46":"Genshiken: Second Season",
"47":"GJ Club",
"48":"Kin-iro Mosaic",
"49":"Kotoura-san",
"50":"Love Live!",
"51":"Minami-ke: Tadaima",
"52":"My Teen Romantic Comedy SNAFU",
"53":"Non Non Biyori",
"54":"Servant x Service",
"55":"Silver Spoon",
"56":"Super Seisyun Brothers",
"57":"Tamako Market",
"58":"Tamayura: More Aggressive",
"59":"WataMote",
"60":"The Wind Rises",
"61":"Yuyushiki",
"62":"Barakamon",
"63":"The Comic Artist and His Assistants",
"64":"Engaged to the Unidentified",
"65":"Free! - Eternal Summer",
"66":"Is the Order a Rabbit?",
"67":"My Neighbor Seki",
"68":"Go! Go! 575",
"69":"Soul Eater Not!",
"70":"Tesagure! Bukatsu-mono Encore",
"71":"Wake Up, Girls!",
"72":"Food Wars!: Shokugeki no Soma",
"73":"Castle Town Dandelion",
"74":"Himouto! Umaru-chan",
"75":"School-Live!",
"76":"Sound! Euphonium",
"77":"Anne Happy",
"78":"Haven't You Heard? I'm Sakamoto",
"79":"Tanaka-kun is Always Listless",
"80":"A Centaur's Life",
"81":"Gabriel DropOut",
"82":"Blend S",
"83":"Uzaki-chan Wants to Hang Out!"
}

horror = {
"17":"Danganronpa: The Animation",
"18":"Dark Cat",
"19":"Demon City Shinjuku",
"20":"Demon Lord Dante",
"21":"Demon Prince Enma",
"22":"Digital Devil Story: Megami Tensei",
"23":"Doomed Megalopolis",
"24":"Elfen Lied",
"25":"Future Diary",
"26":"Gantz",
"27":"Highschool of the Dead",
"28":"Gregory Horror Show",
"29":"Galerians: Rion",
"30":"Genocyber",
"31":"Ghost Hunt",
"32":"Hakaba Kitaro (GeGeGe no Kitaro)",
"33":"Happy Sugar Life",
"34":"Hellsing",
"35":"Hellsing Ultimate",
"36":"Hell Target",
"37":"Higurashi When They Cry",
"38":"Interlude",
"39":"Jigokudou Reikai Tsuushin",
"40":"Judge",
"41":"Kakurenbo: Hide & Seek",
"42":"The Laughing Salesman",
"43":"Laughing Target",
"44":"Le Portrait de Petit Cossette",
"45":"Lily C.A.T.",
"46":"Malice@Doll",
"47":"Mermaid's Forest",
"48":"Mermaid's Scar",
"49":"Mermaid's Forest",
"50":"Mononoke",
"51":"Monster",
"52":"Monster of Frankenstein",
"53":"Mōryō no Hako",
"54":"Night Head Genesis",
"55":"Ogre Slayer",
"56":"Ookami Kakushi",
"57":"Ousama Game",
"58":"Parasyte: The Maxim",
"59":"Pet Shop of Horrors",
"60":"Pupa",
"61":"Puppet Princess",
"62":"Requiem from the Darkness",
"63":"Roots Search",
"64":"Shadow Star Narutaru",
"65":"Shiki",
"66":"Shin Megami Tensei: Tokyo Mokushiroku",
"67":"SoulTaker",
"68":"Terra Formars",
"69":"Terra Formars: Revenge",
"70":"Thriller Restaurant",
"71":"Tokko",
"72":"Tokyo Ghoul",
"73":"Tokyo Majin",
"74":"Tokyo Majin: 2nd Act",
"75":"Twilight of the Dark Master",
"76":"Violence Jack: Harem Bomber",
"77":"Violence Jack: Evil Town",
"78":"Violence Jack: Hell's Wind Hen",
"79":"Wasurenagumo",
"80":"Wicked City",
"81":"Uzumaki"
}

